### ISSUE TITLE
期待能自由拼装POST参数，以提升可定制度

### ISSUE THREAD

**Issue by jhcn** [ma-weihao/MessageForward#1]
RT

**Comment by ma-weihao** [comment]
“自由拼装POST参数”是指目前 priority message 的接口？ `app/src/main/java/cn/quickweather/messageforward/api/MessageToolsApi.kt`

**Comment by jhcn** [comment]
> “自由拼装POST参数”是指目前优先消息的接口？`app/src/main/java/cn/quickweather/messageforward/api/MessageToolsApi.kt`

很遗憾不懂安卓，我指的自由拼装指的是可以在app操作界面设置url,添加headers,body等

**Comment by ma-weihao** [comment]
转发是以短信的形式，不涉及网络接口。
